### ISSUE TITLE
Assigning NUT_EXPORTER_SERVER to the incorrect values?

### ISSUE THREAD

**Issue by tomswartz07** [DRuggeri/nut_exporter#16]
Hi there;

Thanks very much for this project. I've been using it successfully for monitoring my UPS devices.

I've noted an issue while trying to configure a new UPS which is remote to the exporter.

It appears that the NUT_EXPORTER_SERVER value is assigned twice, and as a result it's incorrectly handling the username/host values.

https://github.com/DRuggeri/nut_exporter/blob/master/nut_exporter.go#L25-L29

Is this expected, or perhaps it's an oversight/bug?

Thanks!

**Comment by DRuggeri** [comment]
Thanks for the report, @tomswartz07 - you're right, it was a bug! I've gone ahead and fixed this in v2.3.2 and the pipeline is building for release now.
