### ISSUE TITLE
nut_exporter --version is broken

### ISSUE THREAD

**Issue by ymettier** [DRuggeri/nut_exporter#19]
```
➜ wget https://github.com/DRuggeri/nut_exporter/releases/download/v2.3.4/nut_exporter-v2.3.4-linux-amd64
➜ chmod 755 nut_exporter-v2.3.4-linux-amd64 
➜ ./nut_exporter-v2.3.4-linux-amd64 --version
<no version printed here>
```
I expected a version number to be printed.

Same with linux-arch64 version.
Not tested with other versions.

**Comment by DRuggeri** [comment]
Thanks! I managed to track this down to an issue in the `.goreleaser.yml` file. Should be fixed with the release that's building now!
