### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by therus000** [DRuggeri/nut_exporter#23]
what grafana dashboard used for this exporter?

**Comment by DRuggeri** [comment]
Well, I tried to publish the dashboard over on Grafana cloud, but keep getting some cryptic nonsense error message (`e.context.store is undefined`) which means... not much :-)

BUT! Here it is. I'll also commit it to the repo shortly.

[UPS statistics-1671288821466.json.txt](https://github.com/DRuggeri/nut_exporter/files/10251980/UPS.statistics-1671288821466.json.txt)
