### ISSUE TITLE
exporter metric "promhttp_metric_handler_requests_total metrics" doesn't update

### ISSUE THREAD

**Issue by kondas** [DRuggeri/nut_exporter#25]
Hi, many thanks for creating this great piece of software. 
I found a bug: using version 2.4.2, the exporter metric counters regarding "promhttp_metric_handler_requests_total" always show 0. "promhttp_metric_handler_requests_in_flight" does correctly show inflight requests, and on the app metric endpoint they are updating correctly.
EDIT: I'm using a single exporter with two upsd's, using a similar scrape job
```  - job_name: ups
    static_configs:
      - targets: ['upsd1','upsd2']
    metrics_path: /ups_metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_server
      - source_labels: [__param_server]
        target_label: instance
      - target_label: __address__
        replacement: nut-exporter.local:9199

**Comment by DRuggeri** [comment]
Thanks for the report, @kondas. It turned out this is a side effect of how the registry and handler was built initially. I've updated how it's done in c3517fe6d787597f3bbaed399565caacbd64d24d and just confirmed that the counter's working as expected.

I'll release this soon!
