### ISSUE TITLE
Scraping multiple servers with no UPS name no longer works

### ISSUE THREAD

**Issue by JonyEpsilon** [DRuggeri/nut_exporter#28]
I think the new logic in 2.5.1 for caching the discovered UPS name is causing problems when nut_exporter is being used to connect to multiple servers, each with a single UPS.

I'm scraping endpoints like:

```
http://<monitoring_host>:9199/ups_metrics?server=<nut_server1>&variables=input.voltage%2Cinput.frequency%2Cbattery.charge%2Cups.realpower%2Cups.status

http://<monitoring_host>:9199/ups_metrics?server=<nut_server2>&variables=input.voltage%2Cinput.frequency%2Cbattery.charge%2Cups.realpower%2Cups.status
```

that is to say, multiple servers, but providing UPS names for none of them as they each have a single UPS attached. This used to work, but now I find all scrapes return the same data. I wonder if the name-caching should be done per-server?

**Comment by DRuggeri** [comment]
Hey there, @JonyEpsilon - you're absolutely correct! The caching should be done on a "qualified name" including the server AS WELL AS the UPS name. Embarrassing error on my part...

I've fixed this in 0db81de91aef6926286a01cb16e32325e95be163 and am rolling a release now. Thanks for the report!
