### ISSUE TITLE
How to use and install this awesome exporter?

### ISSUE THREAD

**Issue by sebasdt** [DRuggeri/nut_exporter#29]
Hi all,

It has been a struggle for me on how to use this nut exporter also Get it that its not made for beginners.

I would like to use docker, In the code section I saw a docker file and its not clear for me how to build it so its usable.
what other things are needed to scrape data from the ups to get it working? 

Im using grafana and prometheus to store and display the data. 

**System:**
Pi 2 with basic lite Pi os 32 bit.
single ups.
It functions as a nut server and my goal is to scrape it then send it over to Prometheus.
Grafana will display it in a neat dashboard.

If more information is needed feel free to ask.

**Comment by sebasdt** [comment]
Changed my mind and put the project on hold

**Comment by mpeter50** [comment]
You don't need to use the Dockerfile if you are ok with using one of the prebuilt images: https://github.com/DRuggeri/nut_exporter/tree/master#with-docker
