### ISSUE TITLE
Please bump golang.org/x/sys dependency to support riscv64-freebsd

### ISSUE THREAD

**Issue by clausecker** [DRuggeri/nut_exporter#31]
Greetings!  This project transitively depends on `golang.org/x/sys`, but a version too old to support riscv64-freebsd is taken.  Please bump the dependency using e.g.

    go get golang.org/x/sys@latest

to fix the build on this new architecture.

**Comment by DRuggeri** [comment]
Hi, @clausecker - no problem. I've updated go.mod to 1.18 minimum and included this dependency. On a whim, I attempted to compile with `GOOS=freebsd` and `GOARCH=riskv64` but my runtime told me that's not a valid GOARCH. I'm curious which version you're using?

**Comment by clausecker** [comment]
Hi @DRuggeri, you need go 1.20 for this target to be available.  The minimum go.mod version required for the new `golang.org/x/sys` dependency to build is 1.17.
