### ISSUE TITLE
Feature request: allow using custom UPSD server port

### ISSUE THREAD

**Issue by mpeter50** [DRuggeri/nut_exporter#39]
I think its currently not possible to connect to a NUT UPSD server that is accessible on a non-default port.
If I specifiy the port in the server address (e.g. `nutserver.lan:1234`), the nut.go lib will unconditionally append the default port number to it, and the connection attempt will result in an error message similar to this:
```
error collecting metric Desc{fqName: "network_ups_tools_error", help: "Failure gathering UPS variables", constLabels: {}, variableLabels: []}: address 192.168.0.30:1234:3493: too many colons in address
```

I think the custom port number would be passed as the second argument to `nut.Connect()` [here](https://github.com/DRuggeri/nut_exporter/blob/v3.0.0/collectors/nut_collector.go#L85C28-L85C28).
I wasn't able to test this as locally built containers (even unmodified, on the v3.0.0 git tag) are failing to start.

Would you please consider adding an option for setting the server port number?

**Comment by DRuggeri** [comment]
Thanks for the idea @mpeter50  - I just pushed 5fdea8db6b85c01861c09af27d778038a730b878 which adds this capability and will aim to release soon!

(Sorry for the slow reply on the issue!)
